[window]
opacity = 0.85
padding.x = 10
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Light"
size = 20

[scrolling]
history = 10000
multiplier = 3

# Colors (One Dark)
# Normal colors
[colors.normal]
black = '#1e2127'
red = '#e06c75'
green = '#98c379'
yellow = '#d19a66'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#abb2bf'

# Bright colors
[colors.bright]
black = '#5c6370'
red = '#e06c75'
green = '#98c379'
yellow = '#d19a66'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#ffffff'
