[general]
import = ["~/.config/alacritty/themes/github_dark.toml"]

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"
size = 16
offset.y = 1

[scrolling]
history = 10000
multiplier = 3
